const JOBS = [
  {
    imgUrl: '/images/featured-jobs/burger-king.svg',
    title: 'Copywriter',
    company: 'Burger King',
    location: 'Mineralwells, WV',
    posted: '11 Jan 2022',
    experience: 3,
    type: 'Full Time',
    pay: '$50,000',
    level: 'Entry',
  },
  {
    imgUrl: '/images/featured-jobs/louis-vuitton.svg',
    title: 'iOS Developer',
    company: 'Louis Vuitton',
    location: 'DeKalb, IL',
    posted: '4 Feb 2022',
    experience: 7,
    type: 'Part Time',
    pay: 'Competitive',
    level: 'Senior',
  },
  {
    imgUrl: '/images/featured-jobs/marriott-hotels.svg',
    title: 'Customer Service Agent',
    company: 'Marriott Hotels',
    location: 'Edgard, LA',
    posted: ' 25 Feb 2022',
    experience: 4,
    type: 'Part Time',
    pay: '$25,000',
    level: 'Entry',
  },
  {
    imgUrl: '/images/featured-jobs/mastercard.svg',
    title: 'Account Manager',
    company: 'Mastercard',
    location: 'Stow, MA',
    posted: '1 Mar 2022',
    experience: 2,
    type: 'Full Time',
    pay: '$75,000',
    level: 'Manager',
  },
  {
    imgUrl: '/images/featured-jobs/tiktok.svg',
    title: 'Human Resources Specialist',
    company: 'Tiktok',
    location: 'Denison, IA',
    posted: '24 Mar 2022',
    experience: 9,
    type: 'Full Time',
    pay: '$100,000',
    level: 'Manager',
  },
  {
    imgUrl: '/images/featured-jobs/verizon.svg',
    title: 'Editorial Specialist',
    company: 'Altenwerth, Medhurst and Roberts',
    location: 'Gladewater, TX',
    posted: '31 Mar 2022',
    experience: 7,
    type: 'Full Time',
    pay: 'Competitve',
    level: 'Senior',
  },
];

export default JOBS;
